name: CI/CD Docker

on:
  push:
    branches: [main]

env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/kameleonserver
  VERSION: ${{ github.sha }}
  NAME: go_cicd

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.VERSION }} # runner 설정에서 읽어들일거에요.
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
          secrets: |
            "DATABASE_HOST=${{ secrets.DATABASE_HOST }}"
          #   "DATABASE_ID=${{ secrets.DATABASE_ID }}"
          #   "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}"
          #   "DATABASE_NAME=${{ secrets.DATABASE_NAME }}"
          #   "HOSTNAME=${{ secrets.HOSTNAME }}"
          #   "PORT=${{ secrets.PORT }}"
          #   "FEEADDRESS=${{ secrets.FEEADDRESS }}"
          #   "FEEPRIVATEKEY=${{ secrets.FEEPRIVATEKEY }}"
          #   "ORACLE_CONTRACT_ADDRESS=${{ secrets.ORACLE_CONTRACT_ADDRESS }}"
          #   "FACTORY_CONTRACT_ADDRESS=${{ secrets.FACTORY_CONTRACT_ADDRESS }}"
          #   "KAMELEON_CONTRACT_ADDRESS=${{ secrets.KAMELEON_CONTRACT_ADDRESS }}"

  deploy:
    needs: build
    name: Deploy
    runs-on: [self-hosted, kameleon]
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Docker run
        run: |
          docker stop ${{ env.NAME }} && docker rm ${{ env.NAME }} && docker rmi ${{ env.DOCKER_IMAGE }}:latest
          docker run -d -p 4001:4001 --name go_cicd --restart always ${{ env.DOCKER_IMAGE }}:latest

# docker run -d -p 4001:4001 --name go_cicd -e DATABASE_HOST=${{ secrets.DATABASE_HOST }}  -e DATABASE_ID=${{ secrets.DATABASE_ID }}  -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}  -e DATABASE_NAME=${{ secrets.DATABASE_NAME }}  -e HOSTNAME=${{ secrets.HOSTNAME }}  -e PORT=${{ secrets.PORT }}  -e FEEADDRESS=${{ secrets.FEEADDRESS }}  -e FEEPRIVATEKEY=${{ secrets.FEEPRIVATEKEY }}  -e ORACLE_CONTRACT_ADDRESS=${{ secrets.ORACLE_CONTRACT_ADDRESS }}  -e FACTORY_CONTRACT_ADDRESS=${{ secrets.FACTORY_CONTRACT_ADDRESS }}  -e KAMELEON_CONTRACT_ADDRESS=${{ secrets.KAMELEON_CONTRACT_ADDRESS }} --restart always ${{ env.DOCKER_IMAGE }}:latest
